serpapi.api.key=${serpapi_api_key}
server.search.engine=/search.json?engine=google_jobs
management.endpoints.web.exposure.include=prometheus,health, info
management.metrics.export.prometheus.enabled=true
management.metrics.enable.jvm=false
management.metrics.enable.system=false
management.metrics.enable.process=false
management.metrics.enable.http.server.requests=true
management.metrics.enable.logback=false
management.metrics.enable.datasource=false
management.metrics.enable.cache=false
management.health.diskspace.enabled=false
management.metrics.enable.diskspace=false
management.metrics.enable.tomcat=false
management.metrics.enable.application=false
management.metrics.enable.executor=false
